---
title: Sutty
description: Sutty crea sitios seguros, veloces y visibles
title_separator: "-"
lang: es
dir: ltr
plugins:
- jekyll-locales
- jekyll-drafts-as-metadata
- jekyll-commonmark
- jekyll-relative-urls
- jekyll-purgecss
- jekyll-brotli
- jekyll-gzip
sass:
  style: compressed
css: assets/css/styles.css
logo: assets/images/sutty.svg
exclude:
- package.json
- yarn.lock
- node_modules
- Dockerfile
- Gemfile
- Gemfile.lock
markdown: CommonMark
commonmark:
  options:
  - SMART
  - FOOTNOTES
  extensions:
  - strikethrough
  - autolink
  - table
locales:
- es
- en
permalink: ":title/"
