---
title: Sutty
description: Sutty crea sitios seguros, veloces y visibles
title_separator: "-"
logo: assets/images/logo.png
url: https://sutty.nl
plugins:
- jekyll-locales
- jekyll-drafts-as-metadata
- jekyll-commonmark
- jekyll-relative-urls
- jekyll-seo-tag
- jekyll-purgecss
- jekyll-brotli
- jekyll-gzip
sass:
  style: compressed
exclude:
- package.json
- yarn.lock
- node_modules
- Dockerfile
- Gemfile
- Gemfile.lock
markdown: CommonMark
commonmark:
  options:
  - SMART
  - FOOTNOTES
  - UNSAFE
  extensions:
  - strikethrough
  - autolink
  - table
locales:
- es
- en
redirect: false
permalink: ":title/"
turbolinks:
  enabled: false
social:
  links:
    - https://todon.nl/@sutty
    - https://twitter.com/SuttyWeb
twitter:
  username: SuttyWeb
author:
  twitter: SuttyWeb
