---
title: 145a8e2fbc9f5ffe41b4795e309f6fcc
title_separator: "-"
lang: es
dir: ltr
plugins:
- jekyll-commonmark
- jekyll-relative-urls
- jekyll-brotli
- jekyll-gzip
sass:
  style: compressed
css: assets/css/styles.css
logo: assets/images/sutty.svg
exclude:
- package.json
- yarn.lock
- node_modules
- Dockerfile
- Gemfile
- Gemfile.lock
markdown: CommonMark
commonmark:
  options:
  - SMART
  - FOOTNOTES
  extensions:
  - strikethrough
  - autolink
  - table
i18n:
- es
permalink: ":title/"
theme: 163957ca042ff0a7d7b81e957b61487c
description: abf206bef6331f50c70e04ad8ea22db8abf206bef6331f50c70e04ad8ea22db8
